name: Copy of System resources logger
description: A simple data logger that gets system resources usage from the board and stores them in a database.
ports: []
bricks:
- arduino:dbstorage_tsstore: {}
- arduino:web_ui: {}
icon: 📈
